#!/bin/awk -f

BEGIN { 
	split("one two three four five six seven eight nine", numbers)
	FS = "" # Set field seperator to "" so that NF is the number of characters.
}

{
	# while line contains word number, replace the first word first char with the digit.
	while ( /(one)|(two)|(three)|(four)|(five)|(six)|(seven)|(eight)|(nine)/ ) {
		for (k in numbers)
			pos[index($0, numbers[k])] = numbers[k]

		delete pos[0] # remove not found
		asorti(pos, dest) # sort on index

		# replace the first letter of the first word with the number
		ind = index($0, pos[dest[1]])
		$0 = substr($0, 1, ind - 1) word_to_number(pos[dest[1]]) substr($0, ind + 1)
		split("", pos) # clear pos array
	}
	$0 = gensub(/[^[:digit:]]+/, "", "g") # remove all non digits
	sum += $1 $NF
}

END {
	print sum
}

function word_to_number(word) {
	for (k in numbers)
		if (word == numbers[k])
			return k
	return 0
}

