#!/bin/awk -f

# This only handles the simplest case. It ignores symbols in both the first and last row. This should also double/triple/w/e count each number.

BEGIN {
  line[1] = ""
  line[2] = ""
  line[3] = ""
  FS = ""
}
{
  line[1] = line[2]
  line[2] = line[3]
  line[3] = $0
}
NR > 2 {
  $0 = line[2]
  for (i = 1; i <= NF; i++){
    if ($i ~ /([^[:digit:]\.])/){
      split(line[1], chars, "")
      do_sum(chars, i);
      split(line[2], chars, "")
      do_sum(chars, i);
      split(line[3], chars, "")
      do_sum(chars, i);
    }
  }
}
END {
  print "END: " sum
}

function do_sum(chars, i) {
  # If there is a number in the center there are no other numbers
  # Else there might be numbers surrounding. But they will not touch.
  if (!get_number_around_digit(chars, i)) {
    sum += get_number_around_digit(chars, i - 1)
    sum += get_number_around_digit(chars, i + 1)
  } else {
    sum += get_number_around_digit(chars, i)
  }
}

function get_number_around_digit(line_chars, ind,   number, i) {
  if (line_chars[ind] !~ /[[:digit:]]/) {
    return 0
  }

  number = line_chars[ind]
  for (i = ind + 1; i <= length(line_chars); i++){
    if (line_chars[i] ~ /[[:digit:]]/){
      number = number line_chars[i]
    }
    else {
      break;
    }
  }

  for (i = ind - 1; i > 0; i--){
    if (line_chars[i] ~ /[[:digit:]]/){
      number = line_chars[i] number
    }
    else {
      break;
    }
  }

  return number + 0
}
