#!/bin/awk -f

NR == 1 {
	split($0, lrs, "")
	FS = "[ =(),]+"
	current_inst = "AAA"
}
NR != 1 && NF > 2 {
	inst[$1] = $2 OFS $3
}
END {
	while ( current_inst != "ZZZ" ) {
		if (ind == length(lrs)) ind = 0
		lr = lrs[++ind]
		split(inst[current_inst], lr_inst)
		current_inst = lr_inst[lr == "L" ? 1 : 2]
		step++
	}
	print step
}
